### ISSUE TITLE
Custom user agent

### ISSUE THREAD

**Issue by avishayil** [lucasferreira/react-native-webview-android#13]
Hi,
How can I change the user agent to custom one?
I don't have any knowledge in Android SDK Development.

**Comment by lucasferreira** [comment]
Hi @avishayil 

I'm tried to mimic the API of native RN WebView (https://facebook.github.io/react-native/docs/webview.html) who currently works only for iOS.

I adopted this concept because I made apps both for iOS and Android, so a I need the same API and resources in two platforms.

But it's not harder to implement what you want, you need to adjusts a few lines of code in .java files:
http://stackoverflow.com/questions/11273045/webview-user-agent

Do you think that can help you?

**Comment by avishayil** [comment]
Thanks for the reference, I just don’t have any idea where to put this line, because the MainActivity doesn’t declare any variable as the web view object.

In the link you provided, they say:
mWebView.getSettings().setUserAgentString("My user agent string, here");

I guess that mWebView should be my variable for the object, but it’s not mentioned anywhere in the code.

Like I said, I have zero knowledge in Android SDK development, so it’s almost Chinese to me.
Can you help in that matter?

**Comment by lucasferreira** [comment]
@avishayil 

Inside module files, go to *src/main/java/com/burnweb/rnwebview/RNWebView.java*, them update in some place near by 70 line:

```
...
this.getSettings().setAllowUniversalAccessFromFileURLs(true);
this.getSettings().setLoadsImagesAutomatically(true);
this.getSettings().setBlockNetworkImage(false);
this.getSettings().setBlockNetworkLoads(false);
this.getSettings().setUserAgentString("My user agent string, here"); // <---- add your user agent here...
...
```

Them you can hit again **react-native run-android**.

**Comment by avishayil** [comment]
Thanks, it works great!

**Comment by carobeta** [comment]
It's possible to set the user-agent for all network request? Not only for the webView?
