### ISSUE TITLE
how to listen in scroll event?

### ISSUE THREAD

**Issue by kazaff** [lucasferreira/react-native-webview-android#21]

**Comment by lucasferreira** [comment]
Hi @kazaff 

I'm tried to mimic the API of native RN WebView (https://facebook.github.io/react-native/docs/webview.html) who currently works only for iOS.

I adopted this concept because I made apps both for iOS and Android, so a I need the same API and resources in two platforms.

And as you can see on the docs, listen to scroll event it's not a possibility now, so I can't focus on that new feature by now.

I recommend you to implement that feature on your html/page and them send some actions to RN by some bridge.
