### ISSUE TITLE
Is there any plan to add JSBridge for webView?

### ISSUE THREAD

**Issue by timzaak** [lucasferreira/react-native-webview-android#22]
like [react-native-webview-bridge](https://github.com/alinz/react-native-webview-bridge)
I have found [JsBridge](https://github.com/lzyzsd/JsBridge) for native Android, But I don't know how to intergrate it

**Comment by lucasferreira** [comment]
Hi @timzaak 

I'm try to mimic the API of native RN WebView (https://facebook.github.io/react-native/docs/webview.html) who currently works only for iOS.

I adopted this concept because I made apps both for iOS and Android, so a I need the same API and resources in two platforms.

A currently possibility is using the URL system, sending hashs and capture in onNavigationStateChange event.

If you are in index.html and them add a hash to index.html#callMyFunction as a cheat, you can capture this "url change" in onNavigationStateChange event.

But by the way, I'll try to put this feature in roadmap for next versions releases ;)

**Comment by timzaak** [comment]
@lucasferreira thanks.
